### ISSUE TITLE
When i am trying to use for multiple videos at a time i am getting errorRuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)

### ISSUE THREAD

**Issue by ChirappaVishnupriya** [akhil-rana/virtual-bg#8] opened 2022-12-13 12:50 UTC
ERROR Error: Uncaught (in promise): **RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)**) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69361)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69537)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:43094)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:24082)
    at https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:23905
    at qa.h (http://localhost:4200/vendor.js:29137:414)
    at ta (http://localhost:4200/vendor.js:29101:299)
    at ua.next (http://localhost:4200/vendor.js:29102:91)
    at http://localhost:4200/vendor.js:29127:619
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4544:29)
RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69361)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69537)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:43094)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:24082)
    at https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:23905
    at qa.h (http://localhost:4200/vendor.js:29137:414)
    at ta (http://localhost:4200/vendor.js:29101:299)
    at ua.next (http://localhost:4200/vendor.js:29102:91)
    at http://localhost:4200/vendor.js:29127:619
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4544:29)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:43125)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:24082)
    at https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:23905
    at qa.h (http://localhost:4200/vendor.js:29137:414)
    at ta (http://localhost:4200/vendor.js:29101:299)
    at ua.next (http://localhost:4200/vendor.js:29102:91)
    at http://localhost:4200/vendor.js:29127:619
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4544:29)
    at Y (http://localhost:4200/vendor.js:29127:389)
    at http://localhost:4200/vendor.js:29137:254
    at resolvePromise (http://localhost:4200/polyfills.js:4328:31)
    at http://localhost:4200/polyfills.js:4235:17
    at rejected (http://localhost:4200/vendor.js:378694:89)
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3489:26)
    at Object.onInvoke (http://localhost:4200/vendor.js:440180:33)
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3488:52)
    at Zone.run (http://localhost:4200/polyfills.js:3251:43)
    at http://localhost:4200/polyfills.js:4392:36
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3523:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:440167:33)

**Comment by akhil-rana** [comment] 2022-12-13 13:13
duplicate of #7

**Closed as completed by akhil-rana** 2022-12-13 13:13 UTC
